In [1]:
class deneme:
    def __init__(self,satır,sutun):
        self.satır=satır
        self.sutun=sutun
        import numpy as np
        self.matrix=np.random.rand(self.satır,self.sutun)
        self.sifirmatrix= np.zeros(shape=(4,1))
        self.matrixekleme=np.append(self.sifirmatrix, self.matrix, axis=1)
        self.sonuc=self.matrixekleme.tolist()
    def ters(self):
        import numpy as np
        tryy=self.matrix.transpose()
        return tryy

In [2]:
x=deneme(4,4)
print(x.matrix)


[[0.62566087 0.73460533 0.18096592 0.51874825]
 [0.42410499 0.43881725 0.86495312 0.19058479]
 [0.57291865 0.55115683 0.13498338 0.6521097 ]
 [0.04722341 0.53176933 0.30244142 0.02344014]]


In [3]:
import findspark
findspark.init()

In [4]:
from pyspark.sql import SparkSession,types
from pyspark.sql import SQLContext


In [5]:
spark=SparkSession.builder.master("local").appName("rddtodf").getOrCreate()

In [8]:
sc=spark.sparkContext

In [9]:
a=x.sonuc

In [10]:
rdd4=sc.parallelize(a).toDF(["a","b","c","d"])

In [11]:
import pandas as pd

In [12]:
rdd4.toPandas().set_index("a").transpose()

a        0.0       0.0       0.0       0.0
b   0.625661  0.424105  0.572919  0.047223
c   0.734605  0.438817  0.551157  0.531769
d   0.180966  0.864953  0.134983  0.302441
_5  0.518748  0.190585  0.652110  0.023440

In [13]:
print(x.ters())

[[0.62566087 0.42410499 0.57291865 0.04722341]
 [0.73460533 0.43881725 0.55115683 0.53176933]
 [0.18096592 0.86495312 0.13498338 0.30244142]
 [0.51874825 0.19058479 0.6521097  0.02344014]]


In [14]:
rdd2=sc.parallelize(x.ters())

In [15]:
rdd2.collect()

[array([0.62566087, 0.42410499, 0.57291865, 0.04722341]),
 array([0.73460533, 0.43881725, 0.55115683, 0.53176933]),
 array([0.18096592, 0.86495312, 0.13498338, 0.30244142]),
 array([0.51874825, 0.19058479, 0.6521097 , 0.02344014])]